# Generated by Django 5.0.6 on 2024-06-25 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonHangDetail',
            fields=[
                ('ma_donhang_detail', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('id_nongsan', models.ForeignKey(db_column='IdNongSan', on_delete=django.db.models.deletion.CASCADE, to='app.nongsan')),
                ('ma_donhang', models.ForeignKey(db_column='MaDonHang', on_delete=django.db.models.deletion.CASCADE, to='app.donhang')),
            ],
        ),
    ]
