# Generated by Django 5.0.6 on 2024-06-25 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_donhangdetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donhangdetail',
            options={'managed': False},
        ),
    ]
