# Generated by Django 5.0.6 on 2024-06-26 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_donhangdetail_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='donhangdetail',
            table='donhang_detail',
        ),
    ]
